name: Update Check

env:
  REPO_URL: https://github.com/mozilla/gecko-dev
  REPO_BRANCH: master

on:
  workflow_dispatch:
  schedule:
    - cron: 0 16 * * 1,5

jobs:
  check-update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Get Commit Hash
        id: get-hash
        run: |
          git clone --depth 1 $REPO_URL -b $REPO_BRANCH --single-branch .
          echo "commit_hash=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: Cache and Compare Hash
        id: cache-hash
        uses: actions/cache@v3
        with:
          path: .commit-hash
          key: HEAD-${{ steps.get-hash.outputs.commit_hash }}

      - name: Update Hash
        id: update-hash
        if: steps.cache-hash.outputs.cache-hit != 'true'
        run: |
          echo ${{ steps.get-hash.outputs.commit_hash }} | tee .commit-hash

      - name: Trigger Build
        id: trigger-build
        if: steps.cache-hash.outputs.cache-hit != 'true'
        uses: peter-evans/repository-dispatch@v2
        with:
          event-type: firefox-source-code-update

      - name: Delete Workflow Runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 1
          keep_minimum_runs: 1
